name: example_workflow
on:
  push:
    branches:
      - example_workflow
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: CheckoutCode
        uses: actions/checkout@v2
      - name: Install node and build
        run: npm install
             npm run build
      - name: UploadArtifacts
        uses: actions/upload-artifact@v2 
        with:
          name: artifact
          path: ../../*
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: DownloadArtifacts
        uses: actions/download-artifact@v2
      - name: DeployArtifacts
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'foo-bar.surge.sh'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}