name: main_workflow
on:
  push:
    branches:
      - nodejs_environment_job
jobs:
  linter-execution:
    name: linter-execution
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12]
    steps:
      - name: CheckoutCode
        uses: actions/checkout@v2
      - name: Setting node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: LinterExecution
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: nodejs_environment_job
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true
  test-execution:
    name: test-execution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run jest tests
        run: npm install jest
             npm run test
  environment_test_execution:
    name: environment_test_execution
    runs-on: ubuntu-latest
    steps:
      - name: Test Javascript Hello Action
        uses: adeloyedeji/github-actions-hello@v1.0
        with:
          who-to-greet: ${{ DESTINATION_PERSON }}
        env: 
          DESTINATION_PERSON: ${{ '2DAW' }}