name: react_app_deploy
on:
  push:
    branches:
      - react_app_deploy
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build app
        run: npm install
          npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: .
  deploy:
    name: DeployArtifact
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifact
      - name: Deploy artifacts
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "javisoler.surge.sh"
          project: .
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}