name: react_app_deploy
on:
  push:
    branches:
      - react_app_deploy
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: CheckoutCode
        uses: actions/checkout@v2
      - name: Build app
        run: npm install
          npm run build
      - name: UploadArtifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: .
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: DownloadArtifacts
        uses: actions/download-artifact@v2
        with:
          name: artifact
      - name: DeployArtifacts
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "javisoler.surge.sh"
          project: .
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}